<div class="row">
	<div class="col-20">
		<img src="img/contenido/doc.JPG" alt="">
	</div>
	<div class="col-60">
		<h2>
			Ph. D Luis Leduc
		</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus quod vitae recusandae voluptas dolorem vero mollitia aperiam voluptatem accusantium labore autem rerum aut eius ducimus sed atque aspernatur quas, similique. Asperiores molestias quae autem aliquid minima facere aliquam sint! Eligendi error doloremque expedita iusto repellendus fugiat unde, a excepturi enim.
		</p>
		<h2 class="blue-text">
			luis.leduc@mx-uk-htn.net
		</h2>
	</div>
</div>
<div class="row">
	<div class="col-20">
		<img src="img/contenido/doc.JPG" alt="">
	</div>
	<div class="col-60">
		<h2>
			Ph. D Rafael Mercado
		</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel quo magnam ipsam tempora impedit eum, excepturi voluptas doloribus ipsum! Provident esse vitae pariatur perspiciatis beatae, velit corporis ipsum reiciendis consequatur, ipsam eos fugit nisi quaerat in? Neque minima culpa deleniti iste dolores sapiente libero natus, aut provident, pariatur, beatae, totam.
		</p>
		<h2 class="blue-text">
			rafa.mercado@mx-uk-htn.net
		</h2>
	</div>
</div>