<div class="container">
	<slick dots=true>
	  <div><img src="img/contenido/imagen1.gif"></div>
	  <div><img src="img/contenido/imagen2.gif"></div>
	  <div><img src="img/contenido/imagen3.gif"></div>
	</slick>
	<div class="row">
		<div class="col-30">
			<h1 class="header">About Us</h1>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae repellat dolorum commodi non asperiores molestias aliquid harum debitis facilis, sapiente adipisci nulla repudiandae nisi autem quisquam vero quidem laudantium tempore!
			</p>
		</div>
		<div class="col-70">
			<img src="img/contenido/lab.JPG" alt="ImagenvalevergaS"/>
		</div>
	</div>
</div>
