<slick dots=true>
  <div><img src="img/contenido/htn_slider_2.jpg"></div>
  <div><img src="img/contenido/htn_slider_3.jpg"></div>
  <div><img src="img/contenido/htn_slider_2.jpg"></div>
</slick>
<div class="row">
	<div class="off-45 col-10">
		<h1>about us</h1>
	</div>
</div>
<div class="row">
	<div class="off-15 col-75" >
		<p align="justify">
			MX-UK Heat Treatment Network is a collaboration initiative between Mexico and the United Kingdom for scientific research leading to the development of innovative solutions to industry's needs. To achieve our goal, we rely on expertise exchange between participating academic institutions and industrial partners.
		</p>
	</div>
</div>
<div class="row">
	<div class="off-15 col-75">
		<p align="justify">
			Our activities will begin in the summer of 2015 thanks to the seed funding granted by the CONACYT-British Council Newton Institutional Links Programme for the execution of the core project "Innovative quenching technologies for the manufacture of forged critical components in off-shore structures"  in partnership with Frisa. With the creation of this network, our aim is to grow beyond the time frame and scope of the core project by adding more partners in the future, both academic and industrial.
		</p>
	</div>
</div>
<div class="row">
	<div class="off-40 col-50">
		<h1>"We rely on expertise exchange between participating academic institutions and industrial partners"</h1>
	</div>
</div>
<div class="row">
	<div class="col-40 row">
		<div class="col-100">
			<h1 align="right">articles</h1>
		</div>
		<div class="col-70 off-30">
			<img src="img/contenido/lab.jpg" alt="">
		</div>
		<div class="col-70 off-30">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
		</div>
	</div>
	<div class="col-50">
		<div class="col-100">
			<h1 align="right">contact us</h1>
		</div>
		<div class="off-10 col-90">
			<p align="right">
				Open to all members and registered guests. Interested but not a member?<br>
				Contact: rafa.mercado@mx-uk-htn.net <br>
				UANL <br>
				Monterrey,Nuevo León <br>
			</p>
		</div>
	</div>
</div>
