<?php if ($this->auth->isAuth()) : ?>
<a  href="User/logout">Logout</a>
	ya etsas logueado tututruur shhhoohh
<?php else: ?>
<div class="container">
	<div class="row">
		<div class="col-50 off-25">
			<div class="card">
				<div class="card-head">
					<h2 class="header-card">Sign up</h2>
				</div>
				<form action="User/ajaxSetUser" name="userForm" method="post" novalidate>
					<div class="card-body">
						<div class="row">
							<div class="col-50">
								<input name="name" ng-model="name" type="text" placeholder="name" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="country" ng-model="country" type="text" placeholder="country" ng-required="true">
							</div>
						</div>
							
						<div class="row">
							<div class="col-50">
								<input name="email" ng-model="email" type="email" placeholder="email" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="email_confirm" ng-model="email_confirm" type="email confirmation" placeholder="retype email" ng-required="true">
							</div>
						</div>

						<div class="row">
							<div class="col-50">
								<input name="address" ng-model="address" type="text" placeholder="address" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="university" ng-model="university" type="text" placeholder="university" ng-required="true">
							</div>
						</div>

						<div class="row">
							<div class="col-50">
								<input name="phone" ng-model="phone" type="text" placeholder="phone" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="degree" ng-model="degree" type="text" placeholder="degree" ng-required="true">
							</div>
						</div>
					</div>
					<div class="card-footer">
						<button id="modal_trigger_1" ng-disabled="userForm.$invalid" href="#modal_1" type="submit">send</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div id="modal_1" align="center">
	<h2>Thank you for signing up!</h2>
	<p>We will send you an email with your password soon.</p>
	<br>
	<img width="60px" height="60px" src="img/menu/logo.png">
</div>
<script>
  $("#modal_trigger_1").lightModal({
    overlayDisable: true
	});
</script>

<?php endif; ?>
