<?php if ($this->auth->isAuth()) : ?>
<a  href="User/logout">Logout</a>
	ya etsas logueado tututruur shhhoohh
<?php else: ?>
<div class="container">
	<div class="row">
		<div class="col-50 off-25">
		
		<link rel="stylesheet" type="text/css" href="css/modal.css" />

			<div class="card">
				<div class="card-head">
					<h2 class="header-card">Sign up</h2>
				</div>
				<form action="User/ajaxSetUser" method="post" novalidate>
					<div class="card-body">
						<div class="row">
							<div class="col-50">
								<input name="name" type="text" placeholder="name" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="country" type="text" placeholder="country" ng-required="true">
							</div>
						</div>
							
						<div class="row">
							<div class="col-50">
								<input name="email" type="email" placeholder="email" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="email_confirm" type="email confirmation" placeholder="retype email" ng-required="true">
							</div>
						</div>

						<div class="row">
							<div class="col-50">
								<input name="address" type="text" placeholder="address" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="university" type="text" placeholder="university" ng-required="true">
							</div>
						</div>

						<div class="row">
							<div class="col-50">
								<input name="phone" type="text" placeholder="phone" ng-required="true">
							</div>
							
							<div class="col-50">
								<input name="degree" type="text" placeholder="degree" ng-required="true">
							</div>
						</div>
					</div>
					<div class="card-footer">
						<button type="submit">send</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!--
<button id="trigger" class="trigger-button" type="button">Launch Modal</button>

  <div id="content">
    <h1>Look at me!</h1>
    <p>I'm a modal window.</p>
  </div>
  <script src="js/lightModal.js"></script>
  -->
<?php endif; ?>
