<div class="sub-nav">
	<div class="row no-margin-bot">
		<div class="pull-left off-10 center-items">
			<a href="" class="square-but active">
				Generals
			</a>
		</div>
		<div class="pull-left center-items">
			<a href="" class="square-but">
				Member access
			</a>
		</div>
		<h1 class="blue-text pull-right" style="margin-top: 0">
			research papers
		</h1>
	</div>
</div>
<div class="row" style="margin-top: 60px;" ng-controller="DownloadsCtlr">
	<div class="col-60 off-10">
		<div class="row" ng-repeat="download in downloadables">
			<form action="Downloads/download" method="get">
				<div class="col-30">
					<img class="fill" src="img/contenido/cuadro_rojo.png" alt="Imagen"/>
				</div>
				<div class="col-60">
					<h5 style="margin: 5px 0; color: #BEBCBC">{{download.title}}</h5>
					<h3 style="margin: 5px 0">{{download.area}}</h3>
					<p class="red-text">{{download.author}}</p>
					<p>{{download.description}}</p>
					<input type="hidden" value="{{download.link}}" name="file">
					<button type="submit">Download</button>
				</div>
			</form>
		</div>
	</div>
	<div class="col-20">
		<div class="date-bar">
			<h1 class="blue-text" style="margin-top: 0;">
				articles
			</h1>
		</div>
		<div class="row">
			<ul class="pull-right dates-list">
				<li>2015
					<ul class="months">
						<li>Jan</li>
						<li>Feb</li>
						<li>Mar</li>
						<li>Apr</li>
						<li>May</li>
						<li>June</li>
					</ul>
				</li>
				<li>2016</li>
				<li>2017</li>
				<li>2018</li>
				<li>2019</li>
				<li>2020</li>
			</ul>
		</div>
	</div>
</div>
