<div class="sub-nav">
	<div class="row no-margin-bot">
		<div class="pull-left off-10 center-items">
			<a href="" class="square-but active">
				Generals
			</a>
		</div>
		<div class="pull-left center-items">
			<a href="" class="square-but">
				Member access
			</a>
		</div>
		<h1 class="blue-text pull-right" style="margin-top: 0">
			research papers
		</h1>
	</div>
</div>
<div class="row" style="margin-top: 60px;" ng-controller="DownloadsCtlr">
	<div class="col-60 off-10">
		<div class="row" ng-repeat="download in downloadables">
			<form action="Downloads/download" method="get">
				<div class="col-30">
					<img class="fill" src="img/contenido/cuadro_rojo.png" alt="Imagen"/>
				</div>
				<div class="col-60">
					<h5 style="margin: 5px 0; color: #BEBCBC">{{download.area}}</h5>
					<h3 style="margin: 5px 0; color: black;">{{download.title}}</h3>
					<p class="red-text">{{download.author}}</p>
					<p>{{download.description}}</p>
					<input type="hidden" value="{{download.link}}" name="file">
					<button type="submit">Download</button>
				</div>
			</form>
		</div>
	</div>
	<div class="col-40">
		<vertical-calendar-filter></vertical-calendar-filter>
	</div>
</div>
