<div ng-controller="DownloadsCtlr">
	<div class="sub-nav">
		<div class="row no-margin-bot">
			<div class="pull-left off-10 center-items">
				<a href="Downloads" class="square-but active">
					General
				</a>
			</div>
			<div class="pull-left center-items">
				<a href="Downloads/members" class="square-but">
					Member
				</a>
			</div>
			<h1 class="blue-text pull-right" style="margin-top: 0">
				research papers
			</h1>
		</div>
	</div>
	<div class="row" style="margin-top: 60px;">
		<div class="col-70 off-10">
			<div class="row" ng-repeat="downloadable in downloadables">
				<div class="col-30">
					<img class="fill" ng-src="{{downloadable.image}}" alt="Imagen"/>
				</div>
				<div class="col-60">
					<h5 style="margin: 5px 0; color: #BEBCBC">{{downloadable.area}}</h5>
					<h3 style="margin: 5px 0">{{downloadable.title}}</h3>
					<p class="red-text">{{downloadable.author}} <a class="download" href="{{downloadable.link}}">download</a></p>
					<p class="date">{{downloadable.datePublished | date : short}}<p>
					{{downloadable.description}}
				</div>
			</div>
		</div>
		<div class="col-20">
			<div class="date-bar">
				<h1 class="blue-text" style="margin-top: 0;">
					articles
				</h1>
			</div>
			<div class="row">
				<ul class="pull-right dates-list">
					<li ng-repeat="year in dates.years"><a ng-click="activeYear = $index">{{year}}</a>
						<ul class="months" ng-show="{{activeYear == $index}}">
							<li ng-repeat="month in dates.months[$index]"><a ng-click="filterByDate($index, $parent.$index)">{{monthNames[month]}}</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
