<div class="sub-nav">
	<div class="row no-margin-bot">
		<div class="pull-left off-10 center-items">
			<a href="" class="square-but">
				General
			</a>
		</div>
		<h1 class="blue-text pull-right" style="margin-top: 0">
			upcoming events
		</h1>
	</div>
</div>
<div class="row" style="margin-top: 60px;">
	<div class="col-70 off-10">
		<div class="row">
			
			<div class="col-60">
				<h5 style="margin: 5px 0; color: #BEBCBC">Sintering/Powder Metallurgy</h5>
				<h3 style="margin: 5px 0">Monterrey, N.L.</h3>
				<p class="red-text">Oct. 9 - 11, 2015</p>
				<p class="blue-text">Nave Genera</p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit animi eligendi, officiis veritatis excepturi aperiam error vitae fuga omnis praesentium. Totam vero sit at eligendi minus? Ea consectetur eum tenetur.
			</div>
			<div class="col-30">
				<img class="fill" src="img/contenido/cuadro_rojo.JPG" alt="Imagen"/>
			</div>
		</div>
		<div class="row">
			
			<div class="col-60">
				<h5 style="margin: 5px 0; color: #BEBCBC">Heat Treating</h5>
				<h3 style="margin: 5px 0">Guadalajara, Jal</h3>
				<p class="red-text">Oct. 16 - 18, 2015</p>
				<p class="blue-text">Business Center</p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit animi eligendi, officiis veritatis excepturi aperiam error vitae fuga omnis praesentium. Totam vero sit at eligendi minus? Ea consectetur eum tenetur.
			</div>
			<div class="col-30">
				<img class="fill" src="img/contenido/cuadro_rojo.JPG" alt="Imagen"/>
			</div>
		</div>
		<div class="row">
			
			<div class="col-60">
				<h5 style="margin: 5px 0; color: #BEBCBC">Advanced Metallurgy</h5>
				<h3 style="margin: 5px 0">México, D.F.</h3>
				<p class="red-text">Oct. 9 - 11, 2015</p>
				<p class="blue-text">World Trade Center</p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit animi eligendi, officiis veritatis excepturi aperiam error vitae fuga omnis praesentium. Totam vero sit at eligendi minus? Ea consectetur eum tenetur.
			</div>
			<div class="col-30">
				<img class="fill" src="img/contenido/cuadro_rojo.JPG" alt="Imagen"/>
			</div>
		</div>
	</div>
	<div class="col-20">
		<div class="date-bar">
			<h1 class="blue-text" style="margin-top: 0;">
				calendar
			</h1>
		</div>
		<div class="row">
			<ul class="pull-right dates-list">
				<li>2015
					<ul class="months">
						<li>Jan</li>
						<li>Feb</li>
						<li>Mar</li>
						<li>Apr</li>
						<li>May</li>
						<li>June</li>
					</ul>
				</li>
				<li>2016</li>
				<li>2017</li>
				<li>2018</li>
				<li>2019</li>
				<li>2020</li>
			</ul>
		</div>
	</div>
</div>
